export interface MealPlanDay {
  day: number
  breakfast: string
  lunch: string
  dinner: string
  night: string
  protein: string
}

export const mealPlanData: MealPlanDay[] = [
  // WEEK 1
  {
    day: 1,
    breakfast: "2 puttu + kadala curry (¾ cup)",
    lunch: "Matta rice 1½ cups + mathi curry (120g) + cabbage thoran",
    dinner: "Kappa (1 cup) + mulakushyam",
    night: "Papaya (1 cup) + 1 boiled egg",
    protein: "~72g",
  },
  {
    day: 2,
    breakfast: "3 idlis + sambar",
    lunch: "Rice + thoran (beans) + netholi fry (80g) + buttermilk",
    dinner: "2 dosa + small omelette (1 egg)",
    night: "Banana (2 small) + milk (1 cup)",
    protein: "~65g",
  },
  {
    day: 3,
    breakfast: "Upma + banana",
    lunch: "Rice + vellari pachadi + ayila curry (120g)",
    dinner: "Kanji (1½ cups) + pickle + cherupayar (½ cup)",
    night: "Guava + handful groundnut",
    protein: "~68g",
  },
  {
    day: 4,
    breakfast: "2 wheat dosa + chammanthi",
    lunch: "Rice + cheera thoran + mathi fry (4 pcs)",
    dinner: "Chappathi (2) + egg curry (2 eggs)",
    night: "Papaya + curd (½ cup)",
    protein: "~70g",
  },
  {
    day: 5,
    breakfast: "Pazham porridge (oats/banana/coconut)",
    lunch: "Rice + kumbalanga moru + thoran + netholi curry",
    dinner: "Kappa biriyani (small portion)",
    night: "1 boiled egg + orange",
    protein: "~63g",
  },
  {
    day: 6,
    breakfast: "Appam (2) + mutta roast (1 egg)",
    lunch: "Rice + pavakka fry + parippu curry + mathi curry",
    dinner: "Idiyappam (2) + veg stew",
    night: "Apple + groundnut",
    protein: "~66g",
  },
  {
    day: 7,
    breakfast: "Puttu + cherupayar curry",
    lunch: "Rice + sambar + beetroot thoran + ayila fry",
    dinner: "Kanji + chammanthi podi",
    night: "Banana (1) + milk (1 cup)",
    protein: "~62g",
  },
  // WEEK 2
  {
    day: 8,
    breakfast: "Idiyappam (3) + egg curry (1 egg)",
    lunch: "Rice + thoran (carrot) + mathi curry",
    dinner: "2 wheat dosa + chutney",
    night: "Papaya + 1 boiled egg",
    protein: "~70g",
  },
  {
    day: 9,
    breakfast: "Upma + banana",
    lunch: "Rice + netholi fry + spinach thoran + rasam",
    dinner: "Chappathi (2) + kadala curry",
    night: "Guava + curd",
    protein: "~67g",
  },
  {
    day: 10,
    breakfast: "2 puttu + cherupayar",
    lunch: "Rice + pavakka mezhukkupuratti + parippu + mathi fry",
    dinner: "Kanji + pickle + cowpea (½ cup)",
    night: "Banana + milk",
    protein: "~68g",
  },
  {
    day: 11,
    breakfast: "3 idlis + chammanthi",
    lunch: "Rice + ayila curry + beans thoran",
    dinner: "Kappa + mulakushyam",
    night: "Orange + peanuts",
    protein: "~64g",
  },
  {
    day: 12,
    breakfast: "Appam (2) + mutta roast (1 egg)",
    lunch: "Rice + sambar + cabbage thoran + netholi curry",
    dinner: "2 dosa + chutney",
    night: "Papaya + 1 boiled egg",
    protein: "~71g",
  },
  {
    day: 13,
    breakfast: "Wheat puttu + banana",
    lunch: "Rice + moru curry + cheera thoran + mathi curry",
    dinner: "Kanji + pappadam (1)",
    night: "Apple + curd",
    protein: "~63g",
  },
  {
    day: 14,
    breakfast: "Idiyappam + veg stew",
    lunch: "Rice + thoran + ayila fry",
    dinner: "Chappathi (2) + egg masala (1 egg)",
    night: "Banana + peanuts",
    protein: "~65g",
  },
  // WEEK 3
  {
    day: 15,
    breakfast: "2 puttu + kadala",
    lunch: "Rice + drumstick sambar + mathi fry",
    dinner: "Idiyappam (2) + egg roast",
    night: "Guava + curd",
    protein: "~72g",
  },
  {
    day: 16,
    breakfast: "Dosa (3) + chutney",
    lunch: "Rice + parippu + cabbage thoran + ayila curry",
    dinner: "Kanji + cherupayar",
    night: "Papaya + 1 boiled egg",
    protein: "~70g",
  },
  {
    day: 17,
    breakfast: "Appam + egg curry",
    lunch: "Rice + beans thoran + netholi fry",
    dinner: "Chappathi + veg kurma",
    night: "Banana + groundnut",
    protein: "~61g",
  },
  {
    day: 18,
    breakfast: "Idli (3) + sambar",
    lunch: "Rice + moru curry + pavakka fry + mathi curry",
    dinner: "Kappa (1 cup) + mulakushyam",
    night: "Apple",
    protein: "~64g",
  },
  {
    day: 19,
    breakfast: "Wheat dosa (3) + chammanthi",
    lunch: "Rice + thoran + ayila fry",
    dinner: "Kanji + pickle + cowpea",
    night: "Papaya + milk",
    protein: "~66g",
  },
  {
    day: 20,
    breakfast: "Upma + banana",
    lunch: "Rice + sambar + beetroot thoran + mathi fry",
    dinner: "Egg pulao (1 egg) small",
    night: "Orange + peanuts",
    protein: "~62g",
  },
  {
    day: 21,
    breakfast: "Puttu + cherupayar",
    lunch: "Rice + vellari pachadi + netholi curry",
    dinner: "Idiyappam + stew",
    night: "Banana",
    protein: "~60g",
  },
  // WEEK 4
  {
    day: 22,
    breakfast: "Idiyappam + egg roast",
    lunch: "Rice + mathi curry + cheera thoran",
    dinner: "2 dosa + chutney",
    night: "Papaya + curd",
    protein: "~70g",
  },
  {
    day: 23,
    breakfast: "Upma + banana",
    lunch: "Rice + netholi fry + parippu + beans thoran",
    dinner: "Chappathi + veg kurma",
    night: "Orange",
    protein: "~63g",
  },
  {
    day: 24,
    breakfast: "Appam + veg stew",
    lunch: "Rice + ayila curry + cabbage thoran",
    dinner: "Kanji + pickle",
    night: "Banana + peanuts",
    protein: "~62g",
  },
  {
    day: 25,
    breakfast: "Chicken Day 1: 2 dosa + chicken curry (small)",
    lunch: "Rice + thoran + chicken fry (small 80g)",
    dinner: "Chappathi + leftover curry",
    night: "Papaya",
    protein: "~74g",
  },
  {
    day: 26,
    breakfast: "Idli + sambar",
    lunch: "Rice + pavakka fry + mathi curry",
    dinner: "Kanji + cherupayar",
    night: "Guava + milk",
    protein: "~65g",
  },
  {
    day: 27,
    breakfast: "2 puttu + kadala",
    lunch: "Rice + moru + beetroot thoran + netholi curry",
    dinner: "Idiyappam + omelette",
    night: "Banana",
    protein: "~68g",
  },
  {
    day: 28,
    breakfast: "Wheat dosa + chutney",
    lunch: "Rice + sambar + snake gourd thoran + ayila fry",
    dinner: "Kanji + pickle",
    night: "Apple",
    protein: "~64g",
  },
  {
    day: 29,
    breakfast: "Chicken Day 2: Appam + chicken stew",
    lunch: "Rice + thoran + chicken curry (small)",
    dinner: "2 chappathi + dal",
    night: "Papaya",
    protein: "~75g",
  },
  {
    day: 30,
    breakfast: "Puttu + cherupayar",
    lunch: "Rice + sambar + netholi fry",
    dinner: "Kappa + mulakushyam",
    night: "Banana + curd",
    protein: "~66g",
  },
]
